Repository DevIruka/trip-connect, pull requests merged in 2025-01, with the labels that each got.

#61 🚚 chore: providers 파일 구조 변경.
  src/app/layout.tsx
  src/app/login/action.ts
  src/app/login/layout.tsx
  src/app/providers.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/providers/TanstackQueryProvider.ts
  yarn.lock
Labels: enhancement

#64 🩹 fix : PR 템플릿 수정.
  pull_request_template.md
  src/app/search/page.tsx
Labels: enhancement

#69 🩹 fix : 고장 난 로그인 기능을 고쳤습니다. ✨ feat : getUser라는 함수를 생성하였습니다.
  src/app/auth/callback/route.ts
  src/app/login/action.ts
  src/app/login/page.tsx
  src/app/search/page.tsx
Labels: enhancement

#76 ✨ feat : 검색 상세 및 검색 바 기본적 기능의 구현. 필터링 미완.
  src/app/search/[id]/page.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/store/useSearchStore.ts
  src/utils/decodeUrl.ts
Labels: enhancement

#86 💄 style : 로그인 ui 시안과 같게.
  public/images/google.png
  public/images/kakao.png
  src/app/login/action.ts
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/Input.tsx
Labels: enhancement

#91 💄Style/home
  public/images/back.svg
  public/images/bookmark.svg
  public/images/more-button.svg
  src/app/(home)/[id]/page.tsx
  src/app/(home)/_components/navBar.tsx
  src/app/(home)/_components/qnaHeader.tsx
  src/app/(home)/_hooks/useBookmark.ts
  src/app/(home)/_utils/fetchPosts.ts
  src/app/globals.css
  src/app/post/[id]/page.tsx
  src/app/post/_components/RenderTranslatedHTML.tsx
  src/utils/api/supabase_api/home/fetchBookmarks.ts
  src/utils/api/supabase_api/home/useDelete.ts
  src/utils/api/tanstack/home/BookmarkHooks.ts
  src/utils/api/tanstack/home/useBookmark.ts
  src/utils/api/tanstack/home/usePosts.ts
Labels: enhancement

#94 ✨ feat : response도 검색할 수 있도록 새로운 tanstack 함수 만듦. 🚚move : 파일 구조를 튜터님께 제안받은 대로 수정.
  package.json
  src/app/search/[id]/_types/searchTypes.ts
  src/app/search/[id]/page.tsx
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/page.tsx
  src/data/category.ts
  src/store/useSearchStore.ts
  src/types/supabase.ts
  src/utils/api/supabase_api/search/fetchSearchRequestPosts.ts
  src/utils/api/supabase_api/search/fetchSearchResponsePosts.tsx
  src/utils/api/tanstack/search/useInfiniteSearchRequestPosts.tsx
  src/utils/api/tanstack/search/useInfiniteSearchResponsePosts.tsx
  yarn.lock
Labels: enhancement

#96 ♻️ refactor : topic이랑 연계되게끔 코드를 수정. topic의 타입 지정을 명확하게 수정. 💄style : 검색창 내부 버튼의 위치 지정을 다시
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/page.tsx
  src/data/category.ts
  src/utils/topics.ts
Labels: enhancement

#104 🔨 script : mui 설치 💄 style : 검색 화면의 ui를 시안과 비슷하게. ♻️ refactor : 타입 재지정 및 컴포넌트의 분리.
  package.json
  src/app/login/action.ts
  src/app/search/[id]/_types/searchTypes.ts
  src/app/search/[id]/page.tsx
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/_components/SearchResults.tsx
  src/types/supabase.ts
  src/utils/api/supabase_api/search/fetchSearchRequestPosts.ts
  src/utils/api/supabase_api/search/fetchSearchResponsePosts.tsx
  src/utils/api/tanstack/search/useInfiniteMergedQuery.ts
  src/utils/api/tanstack/search/useInfiniteSearchRequestPosts.tsx
  src/utils/api/tanstack/search/useInfiniteSearchResponsePosts.tsx
  yarn.lock
Labels: enhancement

#106 style : 검색 결과의 수가 표시됨. ♻️ refactor : search 페이지 일부를 ssr화. 🚑fix : getUser 함수 수정.
  package.json
  src/app/layout.tsx
  src/app/login/action.ts
  src/app/search/[id]/page.tsx
  src/app/search/_components/SearchResultComponent.tsx
  src/app/search/_components/SearchResults.tsx
  src/utils/api/supabase_api/fetchUserProfile.ts
  src/utils/api/supabase_api/getUser.ts
  src/utils/api/supabase_api/search/fetchSearchRequestPosts.ts
  src/utils/api/supabase_api/search/fetchSearchResponsePosts.tsx
  src/utils/api/tanstack/search/useInfiniteMergedQuery.ts
  src/utils/api/tanstack/search/useInfiniteSearchRequestPosts.tsx
  src/utils/api/tanstack/search/useInfiniteSearchResponsePosts.tsx
  yarn.lock
Labels: enhancement

#115 🐛 fix: bookmark userId 오류, 비로그인 시 북마크버튼 클릭 시 얼럿
  src/app/(home)/page.tsx
  src/utils/api/tanstack/home/BookmarkHooks.ts
  src/utils/api/tanstack/home/useBookmark.ts
Labels: bug

#117 Feature/crud request
  src/app/mypage/credit/page.tsx
  src/app/request/[id]/page.tsx
  src/app/request/_components/TopicSelector.tsx
  src/app/request/_hooks/useFormState.tsx
  src/app/request/page.tsx
Labels: documentation

#119 ♻️ refactor : 컴포넌트 분리 및, 타입 에러의 수정.
  src/app/login/action.ts
  src/app/login/page.tsx
  src/app/search/[id]/_types/searchTypes.ts
  src/app/search/[id]/page.tsx
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/_components/SearchResultComponent.tsx
  src/app/search/_components/SearchResultCount.tsx
  src/app/search/_components/SearchResults.tsx
  src/app/search/_components/SelectBox.tsx
  src/data/category.ts
  src/utils/topics.ts
Labels: enhancement

#120 💄 style : topicdata에 이모지를 추가.
  src/utils/topics.ts
Labels: enhancement

#130 💄 style : 검색 / 질문 카드 스타일을 시안과 같게
  public/images/a.png
  public/images/coin.svg
  public/images/q.png
  public/images/star.png
  src/app/fonts/Pretendard-Regular.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/_components/RequestDetail.tsx
  src/app/search/_components/ResponseContent.tsx
  src/app/search/_components/SearchResultComponent.tsx
  src/app/search/_components/SearchResultCount.tsx
  src/app/search/_components/SearchResults.tsx
  src/app/search/_components/SelectBox.tsx
  src/app/search/_components/TabDetail.tsx
  src/app/search/_utils/convertTopictoKorean.ts
  src/data/category.ts
  src/utils/api/supabase_api/search/fetchUserNickNames.ts
  src/utils/api/tanstack/search/useUserNickNames.ts
  src/utils/truncateText.ts
Labels: enhancement

#132 💄 style : 경과 시간 표시 및, 답변 단 사람 인수 표시
  src/app/search/_components/RequestDetail.tsx
  src/app/search/_components/SearchResults.tsx
  src/app/search/_components/TimeAgo.tsx
  src/utils/api/supabase_api/search/getResponseCount.ts
  src/utils/api/tanstack/search/useResponseCounts.ts
Labels: enhancement

#136 💄style : 디자이너분 q/a 바탕으로 지적받은 부분 수정 및 댓글 숫자 기능 추가.
  public/images/ic-bookmark.svg
  src/app/search/_components/RequestDetail.tsx
  src/app/search/_components/ResponseContent.tsx
  src/app/search/_components/ResponseDetail.tsx
  src/app/search/_components/SearchResultCount.tsx
  src/app/search/_components/SearchResults.tsx
  src/app/search/_components/SelectBox.tsx
  src/utils/api/supabase_api/search/getCredit.ts
  src/utils/api/supabase_api/search/getResponseCount.ts
  src/utils/api/tanstack/search/useCredit.tsx
  src/utils/api/tanstack/search/useResponseCounts.ts
Labels: enhancement

#146 💄 style : 검색 페이지를 시안과 같게.,
  public/images/a.png
  public/images/ic-help.svg
  public/images/ic-left.svg
  public/images/ic-xmark.svg
  src/app/search/_components/DetailedSearchBar.tsx
  src/app/search/_components/SearchResultComponent.tsx
  src/app/search/page.tsx
Labels: enhancement

#150 Refactor/search page
  public/images/coin.svg
  public/images/ic-location.svg
  public/images/redDot.svg
  src/app/globals.css
  src/app/login/_auth/oauth.ts
  src/app/login/_components/ErrorMessage.tsx
  src/app/login/_components/Login.tsx
  src/app/login/page.tsx
  src/app/search/[id]/_components/DetailedSearchBar.tsx
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/ResponseContent.tsx
  src/app/search/[id]/_components/ResponseDetail.tsx
  src/app/search/[id]/_components/SearchResultComponent.tsx
  src/app/search/[id]/_components/SearchResultCount.tsx
  src/app/search/[id]/_components/SearchResults.tsx
  src/app/search/[id]/_components/SelectBox.tsx
  src/app/search/[id]/_components/TimeAgo.tsx
  src/app/search/[id]/page.tsx
  src/app/search/_components/RecentSearchList.tsx
  src/app/search/_components/RequestDetail.tsx
  src/app/search/_components/ResponseDetail.tsx
  src/app/search/_components/SearchBar.tsx
  src/app/search/_components/SearchToolTip.tsx
  src/app/search/_hooks/useSearchHandlers.tsx
  src/app/search/_utils/calculateDDay.ts
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/components/BlackBtn.tsx
  src/components/BlueBtn.tsx
  src/components/Input.tsx
Labels: enhancement

#151 💄 style : 크레딧 페이지의 스타일을 시안과 같게.
  public/images/goldcoin.svg
  public/images/ic-Close.svg
  src/app/mypage/credit/_components/CreditBalance.tsx
  src/app/mypage/credit/_components/PaymentModal.tsx
  src/app/mypage/credit/_components/PaymentOptions.tsx
  src/app/mypage/credit/page.tsx
  src/components/Header.tsx
Labels: enhancement

#156 🚑 fix : 최근 검색어 저장 안 되는 현상을 해결. 나라명이 제대로 표시되게 변경.
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/_components/RecentSearchList.tsx
  src/app/search/_hooks/useSearchHandlers.tsx
  src/app/search/page.tsx
Labels: enhancement

#161 💄 style : 마이페이지 스타일을 시안과 거의 같게
  src/app/mypage/page.tsx
  src/components/Header.tsx
Labels: enhancement

#166 💄 style : 리뷰 페이지 스타일을 시안과 최대한 같게.
  public/images/ic-arrow.svg
  public/images/threedot.svg
  src/app/review/[response_id]/_components/TimeAgo.tsx
  src/app/review/[response_id]/page.tsx
  src/components/Header.tsx
Labels: enhancement

#170 🚑 fix : 긴급한 타입 에러 수정 및 수정 버튼이 그냥 보이는 거 없앴음.
  src/app/review/[response_id]/_components/TimeAgo.tsx
  src/app/review/[response_id]/page.tsx
Labels: enhancement

#171 Feat/errorloadingpage
  public/images/siren.svg
  public/images/thehand.svg
  public/images/warning.svg
  src/app/auth/callback/route.ts
  src/app/auth/page.tsx
  src/app/error.tsx
  src/app/loading.tsx
  src/app/login/_components/Login.tsx
  src/app/login/_components/Warning.tsx
  src/app/login/action.ts
  src/app/mypage/page.tsx
  src/app/search/[id]/error.tsx
  src/app/search/[id]/loading.tsx
  src/components/Header.tsx
Labels: enhancement

#183 💄 style : 크레딧 관련 스타일 수정
  src/app/mypage/credit/_components/PaymentModal.tsx
  src/app/mypage/credit/_components/PaymentOptions.tsx
  src/app/mypage/page.tsx
Labels: enhancement

#192 🚑 fix : 검색에서 게시물의 2줄로 끊겨서 보이지 않는 문제 해결
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/ResponseContent.tsx
Labels: enhancement

#202 💄 style : 검색 페이지에 샤드 cn으로 바꿈.
  src/app/globals.css
  src/app/search/[id]/_components/DetailedSearchBar.tsx
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/SearchResultComponent.tsx
  src/app/search/[id]/page.tsx
  src/app/search/_components/RecentSearchList.tsx
  src/app/search/_components/TabDetail.tsx
  src/app/search/page.tsx
  src/app/user/[id]/page.tsx
  src/utils/api/supabase_api/user/fetchResponse.ts
  src/utils/api/tanstack/user/useInfiniteUserResponsePosts.ts
  yarn.lock
Labels: enhancement

#209 ✨ feat : 다국어 지원 세팅 완료.
  i18nConfig.js
  package.json
  public/locales/en/login.json
  public/locales/en/translation.json
  public/locales/ko/login.json
  public/locales/ko/translation.json
  src/app/home/_components/categoryPage.tsx
  src/app/home/_components/navBar.tsx
  src/app/layout.tsx
  src/app/login/_components/Login.tsx
  src/app/post/[id]/page.tsx
  src/app/providers.tsx
  src/app/user/[id]/loading.tsx
  src/app/user/[id]/page.tsx
  src/app/user/_components/PostList.tsx
  src/app/user/_components/ResponseItem.tsx
  src/app/user/_components/ReviewItem.tsx
  src/config/i18n.ts
  src/middleware.ts
  src/providers/I18nProvider.tsx
  src/utils/api/supabase_api/user/fetchResponse.ts
  src/utils/api/supabase_api/user/fetchUser.ts
  src/utils/api/tanstack/user/useInfiniteUserResponsePosts.ts
  src/utils/api/tanstack/user/useUserData.ts
  yarn.lock
Labels: enhancement

#216 ✨ feat : 언어 변환 기능 일단은 완료
  i18nConfig.js
  next.config.mjs
  package.json
  public/locales/en/signup.json
  public/locales/en/translation.json
  public/locales/ko/signup.json
  public/locales/ko/translation.json
  src/app/home/page.tsx
  src/app/login/_components/Login.tsx
  src/app/login/page.tsx
  src/app/mypage/language/page.tsx
  src/app/providers.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/config/i18n.ts
  src/config/server/i18n.js
  src/store/languageStore.ts
  yarn.lock
Labels: enhancement

#219 ✨ feat : 검색 페이지의 상세 내용을 뺀 번역 기능 완료.
  public/locales/en/search.json
  public/locales/ko/search.json
  src/app/search/[id]/_components/DetailedSearchBar.tsx
  src/app/search/[id]/_components/SearchResultCount.tsx
  src/app/search/[id]/_components/SelectBox.tsx
  src/app/search/_components/RecentSearchList.tsx
  src/app/search/_components/SearchBar.tsx
  src/app/search/_components/SearchToolTip.tsx
  src/app/search/_components/TabDetail.tsx
  src/config/i18n.ts
  src/store/languageStore.ts
Labels: enhancement

#225 🚑 fix : 카테고리가 영어로 표시되는 문제를 해결.
  src/app/mypage/_components/RequestPostCard.tsx
  src/app/mypage/_components/ResponsePostCard.tsx
  src/app/mypage/_type/type.ts
  src/app/mypage/filters/all/page.tsx
  src/app/mypage/purchase/page.tsx
Labels: enhancement

#238 🚑 fix : route.ts 원복.
  src/app/auth/callback/route.ts
  src/app/login/_components/Login.tsx
Labels: enhancement

#250 ✨ feat : 다른 유저의 마이페이지(user 페이지) 기능 구현 완료.
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/SearchResults.tsx
  src/app/search/[id]/_types/searchTypes.ts
  src/app/user/[id]/page.tsx
  src/app/user/_components/LoadMoreButton.tsx
  src/app/user/_components/PostList.tsx
  src/app/user/_components/RequestItem.tsx
  src/app/user/_components/ResponseItem.tsx
  src/app/user/_components/ReviewItem.tsx
  src/utils/api/supabase_api/user/fetchRequest.ts
  src/utils/api/supabase_api/user/fetchResponse.ts
  src/utils/api/supabase_api/user/fetchReview.ts
  src/utils/api/tanstack/user/useInfiniteUserReview.ts
  src/utils/api/tanstack/user/userInfiniteUserRequestPost.ts
Labels: enhancement

#252 ✨ feat : 포스트의 카드들의 다국어 지원 완료.
  public/locales/en/search.json
  public/locales/ko/search.json
  src/app/home/_components/DDay.tsx
  src/app/search/[id]/_components/DDay.tsx
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/ResponseDetail.tsx
  src/app/search/[id]/_components/SearchResults.tsx
  src/app/search/[id]/_components/TimeAgo.tsx
  src/app/search/_utils/calculateDDay.ts
  src/app/user/[id]/page.tsx
  src/app/user/_components/Header.tsx
  src/app/user/_components/LoadMoreButton.tsx
  src/app/user/_components/ReviewItem.tsx
  src/data/category.ts
  src/data/nation.ts
  src/utils/api/supabase_api/search/fetchSearchResponsePosts.ts
Labels: enhancement

#254 ✨ feat : 검색 페이지에서 번역 덜 된 부분이 있어, 그 부분을 검수. 다른 유저 마이페이지 번역 완료.
  public/locales/en/search.json
  public/locales/en/user.json
  public/locales/ko/search.json
  public/locales/ko/user.json
  src/app/search/[id]/_components/ResponseDetail.tsx
  src/app/user/_components/Header.tsx
  src/app/user/_components/ProfileSection.tsx
  src/app/user/_components/RequestItem.tsx
  src/app/user/_components/ResponseItem.tsx
  src/app/user/_components/ReviewItem.tsx
  src/app/user/_components/TabNavigation.tsx
  src/data/nation.ts
Labels: enhancement

#256 반응형 작업 완료 및 에러 템플릿 분리.
  public/images/email.png
  public/images/ic-mail.svg
  public/locales/en/login.json
  public/locales/ko/login.json
  src/app/home/_components/DDay.tsx
  src/app/login/_components/ErrorMessage.tsx
  src/app/login/_components/Login.tsx
  src/app/login/page.tsx
  src/app/search/[id]/_components/DetailedSearchBar.tsx
  src/app/search/[id]/_components/RequestDetail.tsx
  src/app/search/[id]/_components/ResponseContent.tsx
  src/app/search/[id]/_components/ResponseDetail.tsx
  src/app/search/[id]/_components/SearchResultComponent.tsx
  src/app/search/[id]/_components/SearchResultCount.tsx
  src/app/search/[id]/_components/SearchResults.tsx
  src/app/search/[id]/_components/SelectBox.tsx
  src/app/search/_components/RecentSearchList.tsx
  src/app/search/_components/SearchBar.tsx
  src/app/search/_components/TabDetail.tsx
  src/app/search/_utils/capitalize.ts
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/components/BlueBtn.tsx
  src/components/Input.tsx
Labels: enhancement

#262 💄 style : 여러 페이지의 반응형 완료
  public/images/biglogo.svg
  src/app/auth/callback/route.ts
  src/app/global-error.tsx
  src/app/mypage/credit/_components/CreditBalance.tsx
  src/app/mypage/credit/_components/DesktopPaymentOptions.tsx
  src/app/mypage/credit/_components/PaymentModal.tsx
  src/app/mypage/credit/_components/PaymentOptions.tsx
  src/app/mypage/credit/page.tsx
  src/app/response/_components/MenuBar.tsx
  src/app/search/[id]/error.tsx
  src/app/search/_components/SearchBar.tsx
  src/app/search/_components/SearchToolTip.tsx
  src/app/user/[id]/page.tsx
  src/app/user/_components/Header.tsx
  src/app/user/_components/ProfileSection.tsx
  src/app/user/_components/RequestItem.tsx
  src/app/user/_components/ResponseItem.tsx
  src/app/user/_components/TabNavigation.tsx
  src/app/user/_types/user.ts
  src/components/ErrorTemplate.tsx
  src/components/Header.tsx
  src/constants/pagination.ts
  src/data/images/biglogo.svg
  src/utils/api/supabase_api/fetchUserProfile.ts
  src/utils/api/supabase_api/user/fetchUser.ts
Labels: enhancement
